Conditions:
  IsFailoverRegion: !Not
    - !Equals
      - !Ref 'PrimaryRegionName'
      - !Ref 'AWS::Region'
  IsPrimaryRegion: !Equals
    - !Ref 'PrimaryRegionName'
    - !Ref 'AWS::Region'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: []
    ParameterLabels: {}
  Comments: ''
  CreatedBy: Carter Meyers (AWS)
  Description: This application deploys a Global RDS Aurora cluster.
  LastUpdated: November 29, 2022
  Version: v1.0
Outputs:
  APIFQDN:
    Condition: ''
    Value: !Join
      - ''
      - - !Ref 'AWS::Region'
        - .api.
        - !Ref 'PublicFQDN'
Parameters:
  CodeDownloadURL:
    Default: https://codeload.github.com/aws-samples/amazon-aurora-postgresql-fast-failover-demo/zip/refs/heads/main
    Description: The URL from which the supporting codebase can be downloaded. This
      codebase is used to deploy the demo dashboard.
    Type: String
  DBAdminPassword:
    Description: The password to be used for the RDS Aurora admin account.
    NoEcho: true
    Type: String
  DBAdminUsername:
    Description: The username to be used for the RDS Aurora admin account.
    Type: String
  FailoverFailoverDatabaseSubnetCIDR:
    Default: 10.10.13.0/24
    Description: The CIDR range you wish to use for your failover database subnet.
    Type: String
  FailoverFailoverPrivateSubnetCIDR:
    Default: 10.10.12.0/24
    Description: The CIDR range you wish to use for your failover private subnet.
    Type: String
  FailoverFailoverPublicSubnetCIDR:
    Default: 10.10.11.0/24
    Description: The CIDR range you wish to use for your failover public subnet.
    Type: String
  FailoverKMSKeyID:
    Description: >-
      The KMS key to be used for cross-region data encryption (e.g., RDS Aurora, Secrets
      Manager). This must correspond to a multi-region CMK available in both the primary
      and failover regions. For more information, visit: https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html
    Type: String
  FailoverPrimaryDatabaseSubnetCIDR:
    Default: 10.10.10.0/24
    Description: The CIDR range you wish to use for your primary database subnet.
    Type: String
  FailoverPrimaryPrivateSubnetCIDR:
    Default: 10.10.9.0/24
    Description: The CIDR range you wish to use for your primary private subnet.
    Type: String
  FailoverPrimaryPublicSubnetCIDR:
    Default: 10.10.8.0/24
    Description: The CIDR range you wish to use for your primary public subnet.
    Type: String
  FailoverRegionName:
    Description: The name of the failover region (e.g., us-east-1)
    Type: String
  FailoverVPCCIDR:
    Default: 10.10.8.0/21
    Description: The CIDR range you wish to use for your VPC.
    Type: String
  MainStackName:
    Type: String
  PrimaryFailoverDatabaseSubnetCIDR:
    Default: 10.10.5.0/24
    Description: The CIDR range you wish to use for your failover database subnet.
    Type: String
  PrimaryFailoverPrivateSubnetCIDR:
    Default: 10.10.4.0/24
    Description: The CIDR range you wish to use for your failover private subnet.
    Type: String
  PrimaryFailoverPublicSubnetCIDR:
    Default: 10.10.3.0/24
    Description: The CIDR range you wish to use for your failover public subnet.
    Type: String
  PrimaryKMSKeyID:
    Description: >-
      The KMS key to be used for cross-region data encryption (e.g., RDS Aurora, Secrets
      Manager). This must correspond to a multi-region CMK available in both the primary
      and failover regions. For more information, visit: https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html
    Type: String
  PrimaryPrimaryDatabaseSubnetCIDR:
    Default: 10.10.2.0/24
    Description: The CIDR range you wish to use for your primary database subnet.
    Type: String
  PrimaryPrimaryPrivateSubnetCIDR:
    Default: 10.10.1.0/24
    Description: The CIDR range you wish to use for your primary private subnet.
    Type: String
  PrimaryPrimaryPublicSubnetCIDR:
    Default: 10.10.0.0/24
    Description: The CIDR range you wish to use for your primary public subnet.
    Type: String
  PrimaryRegionName:
    Description: The name of the primary region (e.g., us-east-1)
    Type: String
  PrimaryVPCCIDR:
    Default: 10.10.0.0/21
    Description: The CIDR range you wish to use for your VPC.
    Type: String
  PublicFQDN:
    Description: The FQDN to be used by this application. An Amazon ACM Certificate
      will be issued for this FQDN.
    Type: String
  PublicHostedZoneID:
    Description: The ID of the Route 53 Hosted Zone corresponding to the Service FQDN.
    Type: String
Resources:
  APIFQDNParam:
    Condition: ''
    Properties:
      Description: !Join
        - ''
        - - 'API Gateway Root Resource ID for '
          - !Ref 'AWS::StackName'
          - ' stack'
      Name: !Join
        - ''
        - - /
          - !Ref 'MainStackName'
          - /
          - APIFQDN
      Tier: Standard
      Type: String
      Value: !Join
        - ''
        - - !Ref 'AWS::Region'
          - .api.
          - !Ref 'PublicFQDN'
    Type: AWS::SSM::Parameter
  BasePathMapping:
    DependsOn:
      - DomainName
      - Deployment
      - DeploymentStage
    Properties:
      BasePath: v1
      DomainName: !Join
        - ''
        - - !Ref 'AWS::Region'
          - .api.
          - !Ref 'PublicFQDN'
      RestApiId: !Join
        - ''
        - - '{{resolve:ssm:/'
          - !Ref 'MainStackName'
          - /APIID}}
      Stage: v1
    Type: AWS::ApiGateway::BasePathMapping
  Certificate:
    Properties:
      DomainName: !Join
        - ''
        - - !Ref 'AWS::Region'
          - .api.
          - !Ref 'PublicFQDN'
      DomainValidationOptions:
        - DomainName: !Join
            - ''
            - - !Ref 'AWS::Region'
              - .api.
              - !Ref 'PublicFQDN'
          HostedZoneId: !Ref 'PublicHostedZoneID'
      ValidationMethod: DNS
    Type: AWS::CertificateManager::Certificate
  DNSRecord:
    DependsOn:
      - DomainName
    Properties:
      HostedZoneId: !Ref 'PublicHostedZoneID'
      RecordSets:
        - AliasTarget:
            DNSName: !GetAtt 'DomainName.RegionalDomainName'
            HostedZoneId: !GetAtt 'DomainName.RegionalHostedZoneId'
          Name: !Join
            - ''
            - - !Ref 'AWS::Region'
              - .api.
              - !Ref 'PublicFQDN'
          Type: A
    Type: AWS::Route53::RecordSetGroup
  Deployment:
    Properties:
      Description: Initial Deployment
      RestApiId: !Join
        - ''
        - - '{{resolve:ssm:/'
          - !Ref 'MainStackName'
          - /APIID}}
    Type: AWS::ApiGateway::Deployment
  DeploymentStage:
    DependsOn:
      - Deployment
    Properties:
      DeploymentId: !Ref 'Deployment'
      MethodSettings:
        - CachingEnabled: false
          DataTraceEnabled: true
          HttpMethod: GET
          LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: /~1
          ThrottlingBurstLimit: '5000'
          ThrottlingRateLimit: '10000'
        - CachingEnabled: false
          DataTraceEnabled: true
          HttpMethod: POST
          LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: /~1
          ThrottlingBurstLimit: '5000'
          ThrottlingRateLimit: '10000'
      RestApiId: !Join
        - ''
        - - '{{resolve:ssm:/'
          - !Ref 'MainStackName'
          - /APIID}}
      StageName: v1
    Type: AWS::ApiGateway::Stage
  DomainName:
    DependsOn:
      - Certificate
    Properties:
      DomainName: !Join
        - ''
        - - !Ref 'AWS::Region'
          - .api.
          - !Ref 'PublicFQDN'
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref 'Certificate'
    Type: AWS::ApiGateway::DomainName
